version: '2'
services:
  server:
    build:
      context: ./server-service
      dockerfile: ./Dockerfile
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./server-service/src/:/src
  db:
    image: mysql:8.0
    # restart: always
    environment:
      MYSQL_DATABASE: 'books'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
